from __future__ import annotations

from typing import Any

from .response_models import (
    ActionType,
    PolicyDecision,
    ResponsePriority,
)


class ResponsePolicyEngine:
    """
    Deterministic policy engine for selecting SOC response actions.

    The engine evaluates:
    - severity
    - risk score
    - confidence
    - threat-intelligence verdict
    - MITRE ATT&CK techniques
    - repeat-offender history
    - historical correlation level
    - available observables

    It does not execute actions. It only produces a PolicyDecision.
    """

    CRITICAL_RISK_THRESHOLD = 90
    HIGH_RISK_THRESHOLD = 70
    MEDIUM_RISK_THRESHOLD = 40

    DESTRUCTIVE_ACTIONS = {
        ActionType.BLOCK_IP,
        ActionType.ISOLATE_HOST,
        ActionType.DISABLE_USER,
        ActionType.RESET_PASSWORD,
    }

    CREDENTIAL_ACCESS_TECHNIQUES = {
        "T1003",
        "T1003.001",
        "T1003.002",
        "T1003.003",
        "T1003.004",
        "T1003.005",
        "T1003.006",
        "T1003.007",
        "T1003.008",
        "T1110",
        "T1555",
    }

    EXECUTION_TECHNIQUES = {
        "T1059",
        "T1059.001",
        "T1059.003",
        "T1059.005",
        "T1059.006",
        "T1204",
        "T1204.002",
    }

    COMMAND_AND_CONTROL_TECHNIQUES = {
        "T1071",
        "T1071.001",
        "T1095",
        "T1105",
        "T1219",
    }

    IMPACT_TECHNIQUES = {
        "T1485",
        "T1486",
        "T1490",
        "T1491",
        "T1498",
        "T1529",
    }

    TRUSTED_VERDICTS = {
        "trusted",
        "benign",
        "clean",
        "safe",
        "harmless",
    }

    MALICIOUS_VERDICTS = {
        "malicious",
        "confirmed_malicious",
        "high_risk",
        "critical",
        "suspicious",
    }

    HIGH_CONFIDENCE_VALUES = {
        "high",
        "very high",
        "confirmed",
    }

    LOW_CONFIDENCE_VALUES = {
        "low",
        "very low",
        "unknown",
    }

    def evaluate(
        self,
        incident: dict[str, Any],
    ) -> PolicyDecision:
        """
        Evaluate incident data and return a deterministic PolicyDecision.

        The method accepts the broader incident structure generated by the
        existing SOC pipeline. Missing fields fall back to safe defaults.
        """

        severity = self._normalize_text(
            incident.get("severity"),
            default="UNKNOWN",
        ).upper()

        confidence = self._normalize_text(
            incident.get("confidence"),
            default="Unknown",
        )

        risk_score = self._extract_risk_score(incident)
        intelligence_verdict = self._extract_intelligence_verdict(incident)
        correlation_level = self._extract_correlation_level(incident)
        repeat_offender = self._extract_repeat_offender(incident)
        mitre_ids = self._extract_mitre_ids(incident)

        ip_addresses = self._extract_ip_addresses(incident)
        usernames = self._extract_usernames(incident)
        hostnames = self._extract_hostnames(incident)

        priority = self._determine_priority(
            severity=severity,
            risk_score=risk_score,
            repeat_offender=repeat_offender,
            correlation_level=correlation_level,
        )

        actions: list[ActionType] = []
        rationale: list[str] = []
        matched_policies: list[str] = []

        if intelligence_verdict in self.TRUSTED_VERDICTS:
            self._add_action(actions, ActionType.NO_ACTION)
            rationale.append(
                f"Threat-intelligence verdict is trusted: "
                f"{intelligence_verdict}."
            )
            matched_policies.append("POL-TRUSTED-INTELLIGENCE")

            return PolicyDecision(
                severity=severity,
                risk_score=risk_score,
                confidence=confidence,
                priority=ResponsePriority.P4,
                recommended_actions=actions,
                rationale=rationale,
                matched_policies=matched_policies,
                requires_human_approval=False,
                automatic_execution_allowed=True,
            )

        if risk_score < self.MEDIUM_RISK_THRESHOLD:
            self._add_action(actions, ActionType.MONITOR)
            rationale.append(
                f"Risk score {risk_score} is below the medium-risk "
                f"threshold of {self.MEDIUM_RISK_THRESHOLD}."
            )
            matched_policies.append("POL-LOW-RISK-MONITORING")

        if (
            severity == "CRITICAL"
            or risk_score >= self.CRITICAL_RISK_THRESHOLD
        ):
            self._add_action(actions, ActionType.CREATE_TICKET)
            self._add_action(actions, ActionType.NOTIFY_SOC)
            self._add_action(actions, ActionType.COLLECT_FORENSICS)

            rationale.append(
                "Critical severity or critical risk score requires "
                "immediate escalation and evidence collection."
            )
            matched_policies.append("POL-CRITICAL-ESCALATION")

        elif severity == "HIGH" or risk_score >= self.HIGH_RISK_THRESHOLD:
            self._add_action(actions, ActionType.CREATE_TICKET)
            self._add_action(actions, ActionType.NOTIFY_SOC)

            rationale.append(
                "High-severity incident requires analyst escalation."
            )
            matched_policies.append("POL-HIGH-RISK-ESCALATION")

        elif (
            severity == "MEDIUM"
            or risk_score >= self.MEDIUM_RISK_THRESHOLD
        ):
            self._add_action(actions, ActionType.CREATE_TICKET)
            self._add_action(actions, ActionType.MONITOR)

            rationale.append(
                "Medium-risk incident requires tracking and monitoring."
            )
            matched_policies.append("POL-MEDIUM-RISK-TRACKING")

        if repeat_offender:
            self._add_action(actions, ActionType.CREATE_TICKET)
            self._add_action(actions, ActionType.NOTIFY_SOC)

            rationale.append(
                "Observable is a historical repeat offender."
            )
            matched_policies.append("POL-REPEAT-OFFENDER")

            if ip_addresses:
                self._add_action(actions, ActionType.BLOCK_IP)
                rationale.append(
                    "Repeat-offender IP address is eligible for containment."
                )

        if correlation_level in {"CRITICAL", "HIGH"}:
            self._add_action(actions, ActionType.COLLECT_FORENSICS)
            self._add_action(actions, ActionType.NOTIFY_SOC)

            rationale.append(
                f"Historical correlation level is {correlation_level}."
            )
            matched_policies.append("POL-HISTORICAL-CORRELATION")

        if intelligence_verdict in self.MALICIOUS_VERDICTS:
            self._add_action(actions, ActionType.CREATE_TICKET)
            self._add_action(actions, ActionType.NOTIFY_SOC)

            rationale.append(
                f"Threat-intelligence verdict indicates risk: "
                f"{intelligence_verdict}."
            )
            matched_policies.append("POL-MALICIOUS-INTELLIGENCE")

            if ip_addresses:
                self._add_action(actions, ActionType.BLOCK_IP)
                rationale.append(
                    "Confirmed malicious IP address should be blocked."
                )

        if mitre_ids & self.CREDENTIAL_ACCESS_TECHNIQUES:
            self._add_action(actions, ActionType.COLLECT_FORENSICS)
            self._add_action(actions, ActionType.CREATE_TICKET)

            rationale.append(
                "Credential-access activity requires evidence collection "
                "and account investigation."
            )
            matched_policies.append("POL-CREDENTIAL-ACCESS")

            if usernames:
                self._add_action(actions, ActionType.DISABLE_USER)
                self._add_action(actions, ActionType.RESET_PASSWORD)

                rationale.append(
                    "Affected user account requires containment."
                )

            if hostnames:
                self._add_action(actions, ActionType.ISOLATE_HOST)

                rationale.append(
                    "Credential-access activity on a known host requires "
                    "host isolation."
                )

        if mitre_ids & self.EXECUTION_TECHNIQUES:
            self._add_action(actions, ActionType.COLLECT_FORENSICS)

            rationale.append(
                "Suspicious execution activity requires forensic collection."
            )
            matched_policies.append("POL-SUSPICIOUS-EXECUTION")

            if hostnames and risk_score >= self.HIGH_RISK_THRESHOLD:
                self._add_action(actions, ActionType.ISOLATE_HOST)

                rationale.append(
                    "High-risk execution activity requires host isolation."
                )

        if mitre_ids & self.COMMAND_AND_CONTROL_TECHNIQUES:
            self._add_action(actions, ActionType.COLLECT_FORENSICS)
            self._add_action(actions, ActionType.NOTIFY_SOC)

            rationale.append(
                "Command-and-control activity requires containment and "
                "investigation."
            )
            matched_policies.append("POL-COMMAND-AND-CONTROL")

            if ip_addresses:
                self._add_action(actions, ActionType.BLOCK_IP)

            if hostnames:
                self._add_action(actions, ActionType.ISOLATE_HOST)

        if mitre_ids & self.IMPACT_TECHNIQUES:
            self._add_action(actions, ActionType.ISOLATE_HOST)
            self._add_action(actions, ActionType.NOTIFY_SOC)
            self._add_action(actions, ActionType.CREATE_TICKET)
            self._add_action(actions, ActionType.COLLECT_FORENSICS)

            rationale.append(
                "Impact-stage activity requires immediate containment."
            )
            matched_policies.append("POL-IMPACT-CONTAINMENT")

        if not actions:
            self._add_action(actions, ActionType.MONITOR)

            rationale.append(
                "No containment or escalation policy matched."
            )
            matched_policies.append("POL-DEFAULT-MONITOR")

        actions = self._remove_no_action_conflict(actions)

        requires_approval = any(
            action in self.DESTRUCTIVE_ACTIONS
            for action in actions
        )

        automatic_execution_allowed = not requires_approval

        if self._normalize_text(confidence).lower() in self.LOW_CONFIDENCE_VALUES:
            actions = self._remove_destructive_actions(actions)
            self._add_action(actions, ActionType.MONITOR)
            self._add_action(actions, ActionType.CREATE_TICKET)

            requires_approval = False
            automatic_execution_allowed = True

            rationale.append(
                "Low-confidence evidence prevents automatic containment."
            )
            matched_policies.append("POL-LOW-CONFIDENCE-SAFEGUARD")

        return PolicyDecision(
            severity=severity,
            risk_score=risk_score,
            confidence=confidence,
            priority=priority,
            recommended_actions=actions,
            rationale=rationale,
            matched_policies=matched_policies,
            requires_human_approval=requires_approval,
            automatic_execution_allowed=automatic_execution_allowed,
        )

    def _determine_priority(
        self,
        severity: str,
        risk_score: int,
        repeat_offender: bool,
        correlation_level: str,
    ) -> ResponsePriority:
        if (
            severity == "CRITICAL"
            or risk_score >= self.CRITICAL_RISK_THRESHOLD
            or (
                repeat_offender
                and correlation_level == "CRITICAL"
            )
        ):
            return ResponsePriority.P1

        if (
            severity == "HIGH"
            or risk_score >= self.HIGH_RISK_THRESHOLD
            or repeat_offender
            or correlation_level == "HIGH"
        ):
            return ResponsePriority.P2

        if (
            severity == "MEDIUM"
            or risk_score >= self.MEDIUM_RISK_THRESHOLD
            or correlation_level == "MEDIUM"
        ):
            return ResponsePriority.P3

        return ResponsePriority.P4

    def _extract_risk_score(self, incident: dict[str, Any]) -> int:
        candidates = [
            incident.get("combined_risk_score"),
            incident.get("risk_score"),
            self._nested_get(
                incident,
                "intelligence_summary",
                "risk_score",
            ),
            self._nested_get(
                incident,
                "threat_intelligence",
                "risk_score",
            ),
            self._nested_get(
                incident,
                "reputation",
                "risk_score",
            ),
        ]

        for candidate in candidates:
            try:
                if candidate is not None:
                    return max(0, min(int(float(candidate)), 100))
            except (TypeError, ValueError):
                continue

        return 0

    def _extract_intelligence_verdict(
        self,
        incident: dict[str, Any],
    ) -> str:
        candidates = [
            incident.get("verdict"),
            incident.get("intelligence_verdict"),
            self._nested_get(
                incident,
                "intelligence_summary",
                "verdict",
            ),
            self._nested_get(
                incident,
                "threat_intelligence",
                "verdict",
            ),
            self._nested_get(
                incident,
                "reputation",
                "verdict",
            ),
        ]

        for candidate in candidates:
            if candidate:
                return self._normalize_text(candidate).lower()

        return "unknown"

    def _extract_correlation_level(
        self,
        incident: dict[str, Any],
    ) -> str:
        candidates = [
            incident.get("correlation_level"),
            incident.get("match_level"),
            self._nested_get(
                incident,
                "historical_correlation",
                "match_level",
            ),
            self._nested_get(
                incident,
                "intelligence_summary",
                "historical_correlation",
                "match_level",
            ),
        ]

        for candidate in candidates:
            if candidate:
                return self._normalize_text(candidate).upper()

        return "NONE"

    def _extract_repeat_offender(
        self,
        incident: dict[str, Any],
    ) -> bool:
        candidates = [
            incident.get("is_repeat_offender"),
            incident.get("repeat_offender"),
            self._nested_get(
                incident,
                "historical_correlation",
                "is_repeat_offender",
            ),
            self._nested_get(
                incident,
                "intelligence_summary",
                "historical_correlation",
                "is_repeat_offender",
            ),
        ]

        return any(candidate is True for candidate in candidates)

    def _extract_mitre_ids(
        self,
        incident: dict[str, Any],
    ) -> set[str]:
        raw_values: list[Any] = []

        raw_values.append(incident.get("mitre_ids"))
        raw_values.append(incident.get("mitre_techniques"))
        raw_values.append(incident.get("mitre_attack"))

        result: set[str] = set()

        for raw_value in raw_values:
            if not raw_value:
                continue

            if isinstance(raw_value, str):
                result.add(raw_value.upper())
                continue

            if isinstance(raw_value, dict):
                technique_id = (
                    raw_value.get("id")
                    or raw_value.get("technique_id")
                )

                if technique_id:
                    result.add(str(technique_id).upper())

                continue

            if isinstance(raw_value, list):
                for item in raw_value:
                    if isinstance(item, str):
                        result.add(item.upper())

                    elif isinstance(item, dict):
                        technique_id = (
                            item.get("id")
                            or item.get("technique_id")
                        )

                        if technique_id:
                            result.add(str(technique_id).upper())

        return result

    def _extract_ip_addresses(
        self,
        incident: dict[str, Any],
    ) -> list[str]:
        candidates = [
            incident.get("source_ip"),
            incident.get("ip_addresses"),
            incident.get("ips"),
            self._nested_get(
                incident,
                "indicators_of_compromise",
                "ips",
            ),
            self._nested_get(
                incident,
                "iocs",
                "ips",
            ),
        ]

        return self._flatten_strings(candidates)

    def _extract_usernames(
        self,
        incident: dict[str, Any],
    ) -> list[str]:
        candidates = [
            incident.get("username"),
            incident.get("user"),
            incident.get("users"),
            incident.get("affected_users"),
            self._nested_get(
                incident,
                "extracted_facts",
                "users",
            ),
        ]

        return self._flatten_strings(candidates)

    def _extract_hostnames(
        self,
        incident: dict[str, Any],
    ) -> list[str]:
        candidates = [
            incident.get("hostname"),
            incident.get("host"),
            incident.get("hosts"),
            incident.get("affected_hosts"),
            self._nested_get(
                incident,
                "extracted_facts",
                "hosts",
            ),
        ]

        return self._flatten_strings(candidates)

    @staticmethod
    def _add_action(
        actions: list[ActionType],
        action: ActionType,
    ) -> None:
        if action not in actions:
            actions.append(action)

    def _remove_destructive_actions(
        self,
        actions: list[ActionType],
    ) -> list[ActionType]:
        return [
            action
            for action in actions
            if action not in self.DESTRUCTIVE_ACTIONS
        ]

    @staticmethod
    def _remove_no_action_conflict(
        actions: list[ActionType],
    ) -> list[ActionType]:
        if len(actions) > 1 and ActionType.NO_ACTION in actions:
            return [
                action
                for action in actions
                if action != ActionType.NO_ACTION
            ]

        return actions

    @staticmethod
    def _nested_get(
        data: dict[str, Any],
        *keys: str,
    ) -> Any:
        current: Any = data

        for key in keys:
            if not isinstance(current, dict):
                return None

            current = current.get(key)

        return current

    @staticmethod
    def _flatten_strings(values: list[Any]) -> list[str]:
        result: list[str] = []

        for value in values:
            if value is None:
                continue

            if isinstance(value, str):
                cleaned = value.strip()

                if cleaned and cleaned not in result:
                    result.append(cleaned)

            elif isinstance(value, list):
                for item in value:
                    if isinstance(item, str):
                        cleaned = item.strip()

                        if cleaned and cleaned not in result:
                            result.append(cleaned)

        return result

    @staticmethod
    def _normalize_text(
        value: Any,
        default: str = "",
    ) -> str:
        if value is None:
            return default

        text = str(value).strip()

        return text if text else default